version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: swc_dev_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: swc-web
    ports:
      - '3306:3306'
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
