version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: swc_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: swc-web
    ports:
      - '3306:3306'
    volumes:
      - ./.docker/dbdata:/var/lib/mysql

  redis:
    container_name: swc_redis
    image: redis:alpine
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - '6379:6379'
    restart: unless-stopped
