services:
  mysql:
    image: mysql:8.0
    container_name: swc_testing_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: swc-web-cypress
    ports:
      - '3307:3306'
    volumes:
      - swc_data:/var/lib/mysql

volumes:
  swc_data:
