import { expect, it } from '@jest/globals'

import { getFormattedDescription } from '@/utils/shared/address'

describe('getFormattedDescription', () => {
  it.each([
    [
      {
        streetNumber: '',
        route: '',
        subpremise: '',
        locality: '',
        administrativeAreaLevel1: '',
        administrativeAreaLevel2: '',
        postalCode: '',
        postalCodeSuffix: '',
        countryCode: '',
      },
      '',
    ],
    [
      {
        streetNumber: '',
        route: '',
        subpremise: '',
        locality: '',
        administrativeAreaLevel1: '',
        administrativeAreaLevel2: '',
        postalCode: '',
        postalCodeSuffix: '',
        countryCode: 'US',
      },
      'US',
    ],
    [
      {
        streetNumber: '',
        route: '',
        subpremise: '',
        locality: '',
        administrativeAreaLevel1: '',
        administrativeAreaLevel2: '',
        postalCode: '12345',
        postalCodeSuffix: '',
        countryCode: 'US',
      },
      '12345 US',
    ],
    [
      {
        streetNumber: '',
        route: '',
        subpremise: '',
        locality: '',
        administrativeAreaLevel1: '',
        administrativeAreaLevel2: '',
        postalCode: '12345',
        postalCodeSuffix: '4321',
        countryCode: 'US',
      },
      '12345-4321 US',
    ],
    [
      {
        streetNumber: '',
        route: '',
        subpremise: '',
        locality: '',
        administrativeAreaLevel1: 'MS',
        administrativeAreaLevel2: '',
        postalCode: '12345',
        postalCodeSuffix: '4321',
        countryCode: 'US',
      },
      'MS, 12345-4321 US',
    ],
    [
      {
        streetNumber: '',
        route: '',
        subpremise: '',
        locality: 'STARKVILLE',
        administrativeAreaLevel1: 'MS',
        administrativeAreaLevel2: '',
        postalCode: '12345',
        postalCodeSuffix: '4321',
        countryCode: 'US',
      },
      'STARKVILLE MS, 12345-4321 US',
    ],
    [
      {
        streetNumber: '',
        route: '',
        subpremise: '',
        locality: 'STARKVILLE',
        administrativeAreaLevel1: 'MS',
        administrativeAreaLevel2: '',
        postalCode: '',
        postalCodeSuffix: '4321',
        countryCode: 'US',
      },
      'STARKVILLE MS, US',
    ],
    [
      {
        streetNumber: '',
        route: 'LYNN LN',
        subpremise: '',
        locality: 'STARKVILLE',
        administrativeAreaLevel1: 'MS',
        administrativeAreaLevel2: '',
        postalCode: '12345',
        postalCodeSuffix: '4321',
        countryCode: 'US',
      },
      'LYNN LN, STARKVILLE MS, 12345-4321 US',
    ],
    [
      {
        streetNumber: '110',
        route: 'LYNN LN',
        subpremise: '',
        locality: 'STARKVILLE',
        administrativeAreaLevel1: 'MS',
        administrativeAreaLevel2: '',
        postalCode: '12345',
        postalCodeSuffix: '4321',
        countryCode: 'US',
      },
      '110 LYNN LN, STARKVILLE MS, 12345-4321 US',
    ],
    [
      {
        streetNumber: '110',
        route: 'LYNN LN',
        subpremise: 'APT 338',
        locality: 'STARKVILLE',
        administrativeAreaLevel1: 'MS',
        administrativeAreaLevel2: '',
        postalCode: '12345',
        postalCodeSuffix: '4321',
        countryCode: 'US',
      },
      '110 LYNN LN APT 338, STARKVILLE MS, 12345-4321 US',
    ],
    [
      {
        streetNumber: '110',
        route: '',
        subpremise: 'APT 338',
        locality: 'STARKVILLE',
        administrativeAreaLevel1: 'MS',
        administrativeAreaLevel2: '',
        postalCode: '12345',
        postalCodeSuffix: '4321',
        countryCode: 'US',
      },
      'STARKVILLE MS, 12345-4321 US',
    ],
    [
      {
        streetNumber: '110',
        route: '',
        subpremise: 'APT 338',
        locality: 'STARKVILLE',
        administrativeAreaLevel1: 'MS',
        administrativeAreaLevel2: '',
        postalCode: '12345',
        postalCodeSuffix: '4321',
        countryCode: 'US',
      },
      'STARKVILLE MS, 12345-4321 US',
    ],
  ])('Address %p should return FormattedDescription %p', (input, expected) => {
    expect(getFormattedDescription(input)).toEqual(expected)
  })
})
