export const USER_ACCESS_LOCATION_COOKIE_NAME = 'USER_ACCESS_LOCATION'

export const OVERRIDE_USER_ACCESS_LOCATION_COOKIE_NAME = 'OVERRIDE_USER_ACCESS_LOCATION'

export const USER_ACCESS_LOCATION_COOKIE_MAX_AGE = 1000 * 60 * 60 * 24 * 60 // 60 days
