import { NFTSlug } from '@/utils/shared/nft'
import { requiredEnv } from '@/utils/shared/requiredEnv'

const SWC_SHIELD_NFT_CONTRACT_ADDRESS = requiredEnv(
  process.env.SWC_SHIELD_NFT_CONTRACT_ADDRESS,
  'SWC_SHIELD_NFT_CONTRACT_ADDRESS',
)

const CALL_REPRESENTATIVE_NFT_CONTRACT_ADDRESS = requiredEnv(
  process.env.CALL_REPRESENTATIVE_NFT_CONTRACT_ADDRESS,
  'CALL_REPRESENTATIVE_NFT_CONTRACT_ADDRESS',
)

const I_VOTED_ADDRESS = requiredEnv(
  process.env.I_VOTED_ADDRESS,
  'CALL_REPRESENTATIVE_NFT_CONTRACT_ADDRESS',
)

export const NFT_CONTRACT_ADDRESS: Record<NFTSlug, string> = {
  [NFTSlug.SWC_SHIELD]: SWC_SHIELD_NFT_CONTRACT_ADDRESS,
  [NFTSlug.CALL_REPRESENTATIVE_SEPT_11]: CALL_REPRESENTATIVE_NFT_CONTRACT_ADDRESS,
  [NFTSlug.I_VOTED]: I_VOTED_ADDRESS,
}
