import {
  CRYPTO_RELATED_KEYWORDS,
  QUORUM_API_SORT_KEY,
  QUORUM_API_STARTING_YEAR,
} from '@/inngest/functions/stateLevelBillsCronJob/config'
import { BillKeyDateCategory } from '@/utils/shared/zod/getSWCBills'

export const CRYPTO_RELATED_KEYWORDS_REGEX = new RegExp(
  `\\b(${CRYPTO_RELATED_KEYWORDS.join('|')})\\b`,
  'i',
)

export const QUORUM_API_AUTH_QUERY_PARAMS = {
  api_key: process.env.QUORUM_API_KEY,
  username: process.env.QUORUM_USERNAME,
}

export const QUORUM_API_ENDPOINT = process.env.QUORUM_API_ENDPOINT

export const BUILDER_IO_WRITE_API_ENDPOINT = process.env.BUILDER_IO_WRITE_API_ENDPOINT

const QUORUM_API_US_REGIONS_LIST: number[] = Array.from({ length: 104 }, (_, index) =>
  index >= 40 ? index + 2 : index + 1,
)

export const QUORUM_API_FILTER_QUERY_PARAMS = {
  decode_enums: 'false',
  ...(QUORUM_API_US_REGIONS_LIST.length > 0 && {
    for_supported_regions: QUORUM_API_US_REGIONS_LIST.join(','),
  }),
  for_years: Array.from(
    { length: new Date().getFullYear() - QUORUM_API_STARTING_YEAR + 1 },
    (_, index) => QUORUM_API_STARTING_YEAR + index,
  ).join(','),
  // order_by: QUORUM_API_SORT_KEY,
  title_search: CRYPTO_RELATED_KEYWORDS.join('+OR+'),
}

enum QuorumBillTypes {
  'H.Res.' = 1,
  'S.' = 2,
  'H.R.' = 3,
  'S.Res.' = 4,
  'H.Con.Res.' = 5,
  'S.Con.Res.' = 6,
  'H.J.Res.' = 7,
  'S.J.Res.' = 8,
  'Regulation' = 9,
  'Directive' = 10,
  'Decision' = 11,
  'Nomination' = 12,
  'Other' = 13,
}

export const QUORUM_HOUSE_BILL_TYPES: QuorumBillTypes[] = [
  QuorumBillTypes['H.Con.Res.'],
  QuorumBillTypes['H.J.Res.'],
  QuorumBillTypes['H.R.'],
  QuorumBillTypes['H.Res.'],
]

export const QUORUM_SENATE_BILL_TYPES: QuorumBillTypes[] = [
  QuorumBillTypes['S.'],
  QuorumBillTypes['S.Con.Res.'],
  QuorumBillTypes['S.J.Res.'],
  QuorumBillTypes['S.Res.'],
]

export const QUORUM_BILL_STATUSES = {
  1: 'Action',
  2: 'Withdrawn',
  3: 'Prefiled',
  4: 'Introduced',
  5: 'First Reading',
  6: 'Referred to Committee',
  7: 'Reported by Committee',
  8: 'Reported Unfavorably by Committee',
  9: 'Reported Favorably by Committee',
  10: 'Failed by Committee',
  11: 'Amendment Proposed',
  12: 'Amendment Passed',
  13: 'Second Reading',
  14: 'Third (Final) Reading',
  15: 'Passed House',
  16: 'Passed Senate',
  17: 'Agreed To (Simple Resolution)',
  18: 'Agreed To (Joint Resolution)',
  19: 'Agreed To (Constitutional Amendment Proposal)',
  20: 'Agreed To (Concurrent Resolution)',
  21: 'Enrolled Bill',
  22: 'Replaced With a Substituted Wholesale',
  23: 'Passed House with Changes',
  24: 'Passed Senate with Changes',
  25: 'Conference Report Agreed to by House',
  26: 'Conference Report Agreed to by Senate',
  27: 'Failed House',
  28: 'Failed Senate',
  29: 'Passed Senate, Failed House',
  30: 'Passed House, Failed Senate',
  31: 'Sent to President',
  32: 'Failed Under Suspension',
  33: 'Failed Cloture',
  34: 'Failed to Resolve Differences',
  35: 'Vetoed (No Override Attempt)',
  36: 'Line-item (Partially) Vetoed',
  37: 'Pocket Vetoed',
  38: 'Vetoed & Override Failed in House',
  39: 'Vetoed & Override Failed in Senate',
  40: 'Vetoed & House Overrides (Senate Next)',
  41: 'Vetoed & Senate Overrides (House Next)',
  42: 'Vetoed & Override Passed Senate, Failed in House',
  43: 'Vetoed & Override Passed House, Failed in Senate',
  44: 'Signed by Executive',
  45: 'Veto Overridden',
  46: 'Enacted: 10 Day Rule',
  47: 'Referred to Committee in the Second Chamber.',
  48: 'Hearing Scheduled',
  49: 'Sponsor introductory remarks on measure',
  50: 'Introduced in House',
  51: 'Referred to House committee',
  52: 'Reported by House Committee',
  53: 'Introduced in Senate',
  54: 'Referred to Senate committee',
  55: 'Senate committee/subcommittee hearings',
  56: 'Senate committee/subcommittee markups',
  57: 'Reported by Senate Committee',
  58: 'Senate committee discharged',
  59: 'Senate committee report filed after reporting',
  60: 'Became Public Law',
  61: 'Sequential committee referral',
  62: 'Committee report of an original measure',
  63: 'Committee discharged',
  64: 'Union Calendar assignment',
  65: 'Received in the House',
  66: 'Held at the desk',
  67: 'Motion to Discharge Committee',
  68: 'Rule provides for consideration of',
  69: 'Conference report [free text] filed',
  70: 'Final Passage Under Suspension of the Rules Results',
  71: 'Motion To Reconsider Results',
  72: 'Consideration by House',
  73: 'Debate',
  74: 'Point of order against a motion',
  75: 'Rule provides for consideration of',
  76: 'Placed on House Calendar',
  77: 'Motion to Recommit',
  78: 'Left Unfinished',
  79: 'Motion to Recommit Ordered',
  80: 'Scheduled for Floor',
  81: 'Motion to Recommit Failed',
  82: 'Title Amended',
  83: 'First Reading in Second Chamber',
  84: 'Second Reading in Second Chamber',
  85: 'Third Reading in Second Chamber',
  86: 'Placed on Senate Calendar',
  87: 'Amendment Failed',
  88: 'Defeated',
  89: 'Referred to Subcommittee',
  90: 'Reported out of Subcommittee',
  91: 'Prefiled',
  92: 'Senate Reconsidering',
  93: 'House Reconsidering',
  201: 'Referred to Committee',
  202: 'In Committee Hearings',
  203: 'Under Committee Consideration',
  204: 'Discharged by Committee',
  205: 'Reported by Committee',
  206: 'Calendars',
  207: 'Considered by the Senate',
  208: 'Confirmed by the Senate',
  209: 'Withdrawn by President',
  210: 'Returned to the President',
  211: 'Received in the Senate',
  1000: 'Other',
}

export const QUORUM_BILL_STATUS_TO_CATEGORY_MAP: Partial<
  Record<keyof typeof QUORUM_BILL_STATUSES, BillKeyDateCategory>
> = {
  15: BillKeyDateCategory.BILL_PASSED_LOWER_CHAMBER,
  16: BillKeyDateCategory.BILL_PASSED_UPPER_CHAMBER,
  27: BillKeyDateCategory.BILL_FAILED_LOWER_CHAMBER,
  28: BillKeyDateCategory.BILL_FAILED_UPPER_CHAMBER,
  35: BillKeyDateCategory.PRESIDENT_VETOED,
  36: BillKeyDateCategory.PRESIDENT_VETOED,
  37: BillKeyDateCategory.PRESIDENT_VETOED,
  44: BillKeyDateCategory.PRESIDENT_SIGNED,
}

export const BILL_MAJOR_MILESTONE_TITLE_MAP: Partial<Record<BillKeyDateCategory, string>> = {
  [BillKeyDateCategory.BILL_FAILED_LOWER_CHAMBER]: 'Failed House',
  [BillKeyDateCategory.BILL_FAILED_UPPER_CHAMBER]: 'Failed Senate',
  [BillKeyDateCategory.BILL_PASSED_LOWER_CHAMBER]: 'Passed House',
  [BillKeyDateCategory.BILL_PASSED_UPPER_CHAMBER]: 'Passed Senate',
  [BillKeyDateCategory.PRESIDENT_SIGNED]: 'President Signed',
  [BillKeyDateCategory.PRESIDENT_VETOED]: 'President Vetoed',
}

export const QUORUM_BILL_REGION_MAP = {
  1: 'US Congress',
  2: 'Alabama Legislature',
  3: 'Alaska State Legislature',
  4: 'Arizona State Legislature',
  5: 'Arkansas General Assembly',
  6: 'California State Legislature',
  7: 'Colorado General Assembly',
  8: 'Connecticut General Assembly',
  9: 'Delaware General Assembly',
  10: 'Council of the District of Columbia',
  11: 'Florida Legislature',
  12: 'Georgia General Assembly',
  13: 'Hawaii State Legislature',
  14: 'Idaho State Legislature',
  15: 'Illinois General Assembly',
  16: 'Indiana General Assembly',
  17: 'Iowa General Assembly',
  18: 'Kansas State Legislature',
  19: 'Kentucky General Assembly',
  20: 'Louisiana Legislature',
  21: 'Maine Legislature',
  22: 'Maryland General Assembly',
  23: 'Massachusetts General Court',
  24: 'Michigan Legislature',
  25: 'Minnesota State Legislature',
  26: 'Mississippi Legislature',
  27: 'Missouri General Assembly',
  28: 'Montana Legislature',
  29: 'Nebraska Legislature',
  30: 'Nevada Legislature',
  31: 'New Hampshire General Court',
  32: 'New Jersey Legislature',
  33: 'New Mexico Legislature',
  34: 'New York Legislature',
  35: 'North Carolina General Assembly',
  36: 'North Dakota Legislative Assembly',
  37: 'Ohio General Assembly',
  38: 'Oklahoma Legislature',
  39: 'Oregon Legislative Assembly',
  40: 'Pennsylvania General Assembly',
  42: 'Rhode Island General Assembly',
  43: 'South Carolina Legislature',
  44: 'South Dakota State Legislature',
  45: 'Tennessee General Assembly',
  46: 'Texas Legislature',
  47: 'Utah State Legislature',
  48: 'Vermont General Assembly',
  49: 'Virginia General Assembly',
  50: 'Washington State Legislature',
  51: 'West Virginia Legislature',
  52: 'Wisconsin State Legislature',
  53: 'Wyoming State Legislature',
  54: 'Alabama Local',
  55: 'Alaska Local',
  56: 'Arizona Local',
  57: 'Arkansas Local',
  58: 'California Local',
  59: 'Colorado Local',
  60: 'Connecticut Local',
  61: 'Delaware Local',
  62: 'District of Columbia Local',
  63: 'Florida Local',
  64: 'Georgia Local',
  65: 'Hawaii Local',
  66: 'Idaho Local',
  67: 'Illinois Local',
  68: 'Indiana Local',
  69: 'Iowa Local',
  70: 'Kansas Local',
  71: 'Kentucky Local',
  72: 'Louisiana Local',
  73: 'Maine Local',
  74: 'Maryland Local',
  75: 'Massachusetts Local',
  76: 'Michigan Local',
  77: 'Minnesota Local',
  78: 'Mississippi Local',
  79: 'Missouri Local',
  80: 'Montana Local',
  81: 'Nebraska Local',
  82: 'Nevada Local',
  83: 'New Hampshire Local',
  84: 'New Jersey Local',
  85: 'New Mexico Local',
  86: 'New York Local',
  87: 'North Carolina Local',
  88: 'North Dakota Local',
  89: 'Ohio Local',
  90: 'Oklahoma Local',
  91: 'Oregon Local',
  92: 'Pennsylvania Local',
  93: 'Puerto Rico Local',
  94: 'Rhode Island Local',
  95: 'South Carolina Local',
  96: 'South Dakota Local',
  97: 'Tennessee Local',
  98: 'Texas Local',
  99: 'Utah Local',
  100: 'Vermont Local',
  101: 'Virginia Local',
  102: 'Washington Local',
  103: 'West Virginia Local',
  104: 'Wisconsin Local',
  105: 'Wyoming Local',
}
