export const MAJOR_MILESTONE_CONFIG = {
  HIGHLIGHTED_POINT_SIZE: 40,
  NOT_HIGHLIGHTED_POINT_SIZE: 24,
  POINT_FIXED_SPACING: 20,
  TITLE_FIXED_SPACING: 80,
  TITLE_HEIGHT: 28,
  TITLE_WIDTH: 200,
}

export const MINOR_MILESTONE_CONFIG = {
  POINT_FIXED_SPACING: 30,
  POINT_SIZE: 20,
}
